export const TABLES = {
  USER_PROFILES: 'user_profiles',
  PUBLIC_USER_PROFILES: 'public_user_profiles',
  USER_ROLES: 'user_roles',
  USER_FOLLOWS: 'user_follows',
  USER_PLAYLISTS: 'user_playlists',
  PLAYLIST_SONGS: 'playlist_songs',
  PLAYLIST_COMMENTS: 'playlist_comments',
  PLAYLIST_POSTS: 'playlist_posts',
  FEED_POSTS: 'feed_posts',
  FEED_POST_COMMENTS: 'feed_post_comments',
  FEED_POST_VOTES: 'feed_post_votes',
  FEED_POST_COMMENT_VOTES: 'feed_post_comment_votes',
  PLAYLIST_COMMENT_VOTES: 'playlist_comment_votes',
  PLAYLIST_POST_VOTES: 'playlist_post_votes',
  SONG_RATINGS: 'song_ratings',
  SONG_COMMENTS: 'song_comments',
  SONG_COMMENT_VOTES: 'song_comment_votes',
  SONG_TAGS: 'song_tags',
  SONG_TAGS_DICTIONARY: 'song_tags_dictionary',
  ALLOWED_PLACES: 'allowed_places',
  MALL_SCHEDULE: 'mall_schedule',
  ACCESS_REQUESTS: 'access_requests',
  QUEUE_RULES: 'queue_rules',
  QUEUE_ENTRIES: 'queue_entries',
  GAME_SESSIONS: 'game_sessions',
  USER_ALL_SCORES: 'user_all_scores',
  USER_FAVORITE_SONGS: 'user_favorite_songs',
  USER_MOST_PLAYED_SONGS: 'user_most_played_songs',
  USER_ATTRIBUTIONS: 'user_attributions',
  USER_ACTIVITY_NOTIFICATIONS: 'user_activity_notifications',
  AUDIT_LOGS: 'audit_logs',
  CONTACT_REPORTS: 'contact_reports',
  NOTIFICATIONS: 'notifications',
  USER_NOTIFICATION_READS: 'user_notification_reads',
  IMPORT_SESSIONS: 'import_sessions',
  PLACES_REGIONS: 'places_regions',
};

export const BUCKETS = {
  COMMUNITY_MEDIA: 'community-media',
  SONG_JACKETS: 'song_jackets',
  PROFILE_PICTURES: 'profile-pictures',
  CONTACT_UPLOADS: 'contact_uploads',
  POST_IMAGES: 'community-media',
};
