export const LIMITS = {
  FEED_ACTIVITY: 12,
  RECENT_DISCUSSIONS: 10,
  SUGGESTED_PLAYERS: 20,
  NOTIFICATION_POOL: 30,
  PROFILE_POSTS: 20,
  FEED_POSTS: 10,
  PLAYER_POOL_SIZE: 150,
  COMMENT_POOL: 30,
};
